### ISSUE TITLE
Замечания по radix

### ISSUE THREAD

**Issue by sergey-shambir** [AniSkyWorker/radix#1]
Коэффициент 1, т.к. остались несущественные замечания
### Несущественные замечания
- в функции StrElemToInt переменная digit не проинициализирована, возможно, её лучше объявлять 3 раза по месту использования.
- сам метод `StrElemToInt` лучше назвать `DigitToInt`
- метод `IntToStrElem` переименовать в `IntToDigit`, расставить фигурные скобки.
- в функции IsZeroNumber лучше использовать [std::all_of](http://en.cppreference.com/w/cpp/algorithm/all_any_none_of)
- название функции `GetConvertNumInStr` содержит два глагола.
- `return result += '0';` ненужная конструкция, проще `return "0"`, и `std::string result` объявить ниже.
- в условии `if (notation.length() > C_MIN_NOTATION)` лучше не переиспользовать константу, а завести новую. Также можно использовать `std::any_of` вместо цикла.

**Comment by AniSkyWorker** [comment]
исправлено
